packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - electron
  - esbuild
  - onnxruntime-node

patchedDependencies:
  '@readium/navigator-html-injectables@2.8.4': patches/@readium__navigator-html-injectables@2.8.4.patch
  '@readium/navigator@2.11.1': patches/@readium__navigator@2.11.1.patch
