module.exports = {
  appId: "io.github.cynicalight.reader",
  productName: "Reader",
  directories: { output: "../../release" },
  files: ["dist/**/*", "package.json"],
  extraResources: [{ from: "staging", to: ".", filter: ["**/*"] }],
  asar: true,
  npmRebuild: false,
  publish: null,
  protocols: [{ name: "Reader", schemes: ["reader"] }],
  mac: {
    target: ["dmg"],
    category: "public.app-category.books",
    identity: "-",
    hardenedRuntime: false,
    notarize: false,
    artifactName: "Reader-${version}-mac-${arch}.${ext}",
  },
  dmg: { sign: false },
  win: {
    target: ["nsis"],
    signAndEditExecutable: false,
    artifactName: "Reader-${version}-win-${arch}.${ext}",
  },
  nsis: {
    oneClick: false,
    perMachine: false,
    allowToChangeInstallationDirectory: true,
    deleteAppDataOnUninstall: false,
  },
};
